=== Lucam9815/OMIntegrationFOM/TOMIntegrationFOM.module/Schemas/ApplicationConfig.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema 
xmlns="http://www.w3.org/2001/XMLSchema" 
xmlns:tns="http://it.fastweb.com.org/COM/ApplicationConfig/internal/schema" 
elementFormDefault="qualified" 
targetNamespace="http://it.fastweb.com.org/COM/ApplicationConfig/internal/schema">

	<element name="ApplicationConfig" type="tns:ApplicationConfigComplexType"/>

    
    <complexType name="ApplicationConfigComplexType">
    	<sequence>
    		<element maxOccurs="1" minOccurs="0" name="ProjectName" type="string" />
    		<element maxOccurs="1" minOccurs="0" name="EnableInspector" type="boolean"/>
    		<element maxOccurs="1" minOccurs="0" name="Others">
    			<complexType>
    				<sequence>
    					<element maxOccurs="unbounded" minOccurs="0" name="Param" type="tns:KeyValuePairComplexType" />
    				</sequence>
    			</complexType>
    		</element>
    	</sequence>
    	<attribute name="Application" type="string"/>
    </complexType>


    <complexType name="KeyValuePairComplexType">
    	<sequence>
    		<element maxOccurs="1" minOccurs="1" name="Key" type="string"/>
    		<element maxOccurs="1" minOccurs="1" name="Value" type="string"/>
    	</sequence>
    </complexType>
</schema>

=== Lucam9815/OMIntegrationFOM/TOMIntegrationFOM.module/File/ApplicationConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:ApplicationConfig Application="" xmlns:tns="http://it.fastweb.com.org/COM/ApplicationConfig/internal/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://it.fastweb.com.org/COM/ApplicationConfig/internal/schema ../../COM.Shared.Global/Schemas/Internal/ApplicationConfig.xsd ">
	<tns:Others>
		<tns:Param>
			<tns:Key>SuccessReply</tns:Key>
			<tns:Value>tibco.aff.orchestrator.planItem.execute.reply</tns:Value>
		</tns:Param>
		<tns:Param>
			<tns:Key>SuspendReply</tns:Key>
			<tns:Value>tibco.aff.orchestrator.planItem.suspend.reply</tns:Value>
		</tns:Param>
		<tns:Param>
			<tns:Key>ActivateReply</tns:Key>
			<tns:Value>tibco.aff.orchestrator.planItem.execute.reply</tns:Value>
		</tns:Param>
		<tns:Param>
			<tns:Key>Milestone</tns:Key>
			<tns:Value>tibco.aff.orchestrator.planItem.milestone.notify.request</tns:Value>
		</tns:Param>
		<tns:Param>
			<tns:Key>Failed</tns:Key>
			<tns:Value>tibco.aff.orchestrator.planItem.execute.reply</tns:Value>
		</tns:Param>
		<tns:Param>
			<tns:Key>SetUDF</tns:Key>
			<tns:Value>tibco.aff.tds.plan.request</tns:Value>
		</tns:Param>
		<tns:Param>
			<tns:Key>GetUDF</tns:Key>
			<tns:Value>tibco.aff.tds.plan.read.request</tns:Value>
		</tns:Param>
	</tns:Others>
</tns:ApplicationConfig>
